    %% Plot first three coordinates (g - 1 number of canonical variates)
    figure()
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),3), 2, 'r')
    hold on
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),3), 2, 'b')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),3),2, 'g')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),3), 2, 'k')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),3), 2, 'm')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),1),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),3), 2, 'y')
    
    
%     scatter3(fltPatternArray_Testing_Canonical(1,1),...
%         fltPatternArray_Testing_Canonical(1,2), ...
%         fltPatternArray_Testing_Canonical(1,3), 28, 'k', 'x')
%     
%     scatter3(fltPatternArray_Testing_Canonical(2,1),...
%         fltPatternArray_Testing_Canonical(2,2), ...
%         fltPatternArray_Testing_Canonical(2,3), 28, 'r', 'x')
%     
%     scatter3(fltPatternArray_Testing_Canonical(3,1),...
%         fltPatternArray_Testing_Canonical(3,2), ...
%         fltPatternArray_Testing_Canonical(3,3), 28, 'g','x')
%     
%     scatter3(fltPatternArray_Testing_Canonical(4,1),...
%         fltPatternArray_Testing_Canonical(4,2), ...
%         fltPatternArray_Testing_Canonical(4,3), 28, 'y','x')
%     
%     scatter3(fltPatternArray_Testing_Canonical(5,1),...
%         fltPatternArray_Testing_Canonical(5,2), ...
%         fltPatternArray_Testing_Canonical(5,3), 28, 'b', 'x')
%     
%     scatter3(fltPatternArray_Testing_Canonical(6,1),...
%         fltPatternArray_Testing_Canonical(6,2), ...
%         fltPatternArray_Testing_Canonical(6,3), 28, 'm', 'x')
    
    xlabel('ECV #1')
    ylabel('ECV #2')
    zlabel('ECV #3')
    title('Extended Canonical Variates')
    hold off
    legend('Contact Binary', 'RRab', 'Delta Scu / SX Phe', 'Algol', 'RRc', 'None')

    
    
        %% Plot first three coordinates (g - 1 number of canonical variates)
    figure()
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),4),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),3), 4, 'r')
    hold on
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),3),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),4), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),5), 4, 'b')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),3),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),4), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),5), 4, 'g')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),3),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),4), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),5), 4, 'k')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),3),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),4), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),5), 4, 'm')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),3),...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),4), ...
        ECVAm.CanonicalVariates(strcmp(grpSource_TrainCross, 'No Variablity'),5), 4, 'y')
    xlabel('ECV #1')
    ylabel('ECV #2')
    zlabel('ECV #3')
    title('Extended Canonical Variates')
    hold off
    legend('Contact Binary', 'RRab', 'Delta Scu / SX Phe', 'Algol', 'RRc', 'None')
    
        
        %% Plot first three coordinates (g - 1 number of canonical variates)
    figure()
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'Contact Binary'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Contact Binary'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Contact Binary'),3), 4, 'r')
    hold on
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'RRab'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'RRab'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'RRab'),3), 4, 'b')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'Delta Scu / SX Phe'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Delta Scu / SX Phe'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Delta Scu / SX Phe'),3), 4, 'g')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'Algol'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Algol'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'Algol'),3), 4, 'k')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'RRc'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'RRc'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'RRc'),3), 4, 'm')
    scatter3(ECVAm.CanonicalVariates(strcmp(grpSource, 'No Variablity'),5),...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'No Variablity'),2), ...
        ECVAm.CanonicalVariates(strcmp(grpSource, 'No Variablity'),3), 4, 'y')
    xlabel('ECV #1')
    ylabel('ECV #2')
    zlabel('ECV #3')
    title('Extended Canonical Variates')
    hold off
    legend('Contact Binary', 'RRab', 'Delta Scu / SX Phe', 'Algol', 'RRc', 'None')
    
    %%===========================================================
    % Make a movie
    daspect([1,1,.3]);axis tight; 
    OptionZ.FrameRate=15;OptionZ.Duration=7.5;OptionZ.Periodic=true; 
    CaptureFigVid([-20,10;-110,10;-190,80;-290,10;-380,10], 'ExtendedCanonicalVariates',OptionZ)
    
    
    
    
    
        %% Plot first three coordinates (g - 1 number of canonical variates)
    figure()
    scatter3(canonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),1),...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),2), ...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Contact Binary'),3), 4, 'r')
    hold on
    scatter3(canonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),1),...
        canonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),2), ...
        canonicalVariates(strcmp(grpSource_TrainCross, 'RRab'),3), 4, 'b')
    scatter3(canonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),1),...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),2), ...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Delta Scu / SX Phe'),3), 4, 'g')
    scatter3(canonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),1),...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),2), ...
        canonicalVariates(strcmp(grpSource_TrainCross, 'Algol'),3), 4, 'k')
    scatter3(canonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),1),...
        canonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),2), ...
        canonicalVariates(strcmp(grpSource_TrainCross, 'RRc'),3), 4, 'm')
    xlabel('ECV #1')
    ylabel('ECV #2')
    zlabel('ECV #3')
    title('Extended Canonical Variates')
    hold off
    legend('Contact Binary', 'RRab', 'Delta Scu / SX Phe', 'Algol', 'RRc')